import type { BoardSpec, InventoryItem } from "./types";

export const DEFAULT_BOARD: BoardSpec = {
  id: "round-board-300",
  label: "Round board · 300 mm",
  shape: "circle",
  diameterMm: 300,
  marginMm: 22,
  minSpacingMm: 6,
  frameId: "charcuterie_board",
  calibrated: false,
};

export const DEFAULT_INVENTORY: InventoryItem[] = [
  {
    id: "berry",
    label: "Berry",
    pluralLabel: "Berries",
    color: "#7f285b",
    edgeColor: "#481333",
    shape: "cluster",
    footprintMm: 22,
    sourceZone: "tray.berries",
    graspProfile: "soft-small",
    available: 12,
    enabled: true,
  },
  {
    id: "cheese",
    label: "Cheese cube",
    pluralLabel: "Cheese cubes",
    color: "#f2c84b",
    edgeColor: "#b17a14",
    shape: "square",
    footprintMm: 28,
    sourceZone: "tray.cheese",
    graspProfile: "rigid-medium",
    available: 12,
    enabled: true,
  },
  {
    id: "cracker",
    label: "Cracker",
    pluralLabel: "Crackers",
    color: "#dca864",
    edgeColor: "#99642d",
    shape: "disc",
    footprintMm: 38,
    sourceZone: "tray.crackers",
    graspProfile: "fragile-wide",
    available: 8,
    enabled: true,
  },
  {
    id: "grape",
    label: "Grape",
    pluralLabel: "Grapes",
    color: "#617b3d",
    edgeColor: "#344920",
    shape: "circle",
    footprintMm: 24,
    sourceZone: "tray.grapes",
    graspProfile: "soft-small",
    available: 10,
    enabled: true,
  },
  {
    id: "salami",
    label: "Salami round",
    pluralLabel: "Salami rounds",
    color: "#b94f52",
    edgeColor: "#743033",
    shape: "disc",
    footprintMm: 42,
    sourceZone: "tray.salami",
    graspProfile: "fragile-wide",
    available: 8,
    enabled: false,
  },
  {
    id: "olive",
    label: "Olive",
    pluralLabel: "Olives",
    color: "#403f25",
    edgeColor: "#1f2112",
    shape: "circle",
    footprintMm: 24,
    sourceZone: "tray.olives",
    graspProfile: "soft-small",
    available: 10,
    enabled: false,
  },
];
