lerobot-record \
   --robot.type=seeed_b601_rs_follower \
   --robot.port=can0 \
   --robot.id=follower1 \
   --robot.can_adapter=socketcan \
   --robot.cameras="{ front: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30, fourcc: "MJPG"}, side: {type: opencv, index_or_path: 2, width: 640, height: 480, fps: 30, fourcc: "MJPG"}}" \
   --teleop.type=rebot_arm_102_leader \
   --teleop.port=/dev/ttyUSB0 \
   --teleop.id=rebot_arm_102_leader \
   --display_data=true \
   --dataset.repo_id=seeed_rebot_b601_rs/orange-fixed-50 \
   --dataset.num_episodes=50 \
   --dataset.single_task="Grab the black cube" \
   --dataset.push_to_hub=false \
   --dataset.episode_time_s=15 \
   --dataset.reset_time_s=7
